### ISSUE TITLE
Logging errors with both Škoda Fabias & Polo [Error in cmd after competing stage.]

### ISSUE THREAD

**Issue by nlabiris** [soong-construction/dirt-rally-time-recorder#56] opened 2021-01-17 17:08 UTC
Hello

I got the error in the screenshot after completing a stage. I checked the timerecord.log file but mo exception is saved there so I just saved a screenshot with the error.

The track was Te Awanga Sprint Forward and the car that I used was the  VW Polo GTI R5.

Despite the error, the 2 .bat files are generated and I can save the lap time.

![image](https://user-images.githubusercontent.com/13470357/104850347-39833a80-58f7-11eb-89e9-872af1a1d3d0.png)

**Comment by maxbechtold** [comment] 2021-01-17 18:35
Hi @nlabiris, thanks for posting. This seems to be related to the special 'S' in "Škoda". Probably your terminal doesn't work with the UTF-8 encoding. Indeed it seems to look it up in a Greek codepage (CP1253), maybe your system's locale?

Do you use the bundled .exe or are you running through your Python environment - if so, which command are you using? You might need to force it to use UTF-8. I'd be curious to find out if the latest [.exe version](https://github.com/soong-construction/dirt-rally-time-recorder/releases/download/v2.10.2/timerecorder-dirt-rally-2.0.zip) works on your system, maybe you find time to test it?

If you could upload your `timerecord.log` or parts thereof anyway, I'd appreciate - the screenshot works, but it's a bit hard to read.

**Comment by maxbechtold** [comment] 2021-01-17 18:54
My system is set to CodePage 1252 (Powershell: `[System.Text.Encoding]::Default`)

If I bundle for DR2 manually (`sh resources/build-local.sh dr2`, cf. develop.md) I can run it in a cmd window just fine with the Škoda telemetry: 

```
timerecorder-dr2>python -m timerecorder.timerecord
Starting dirt-rally-time-recorder 2.10.2
Found 156 tracks and 57 cars
Checking laptimes database
Waiting for data on 127.0.0.1:20778
TRACK: Sweet Lamb
Ambiguous car data, 2 matches
Škoda Fabia R5: SEQUENTIAL shifting, 5 speed, with HANDBRAKE
Volkswagen Polo GTI R5: SEQUENTIAL shifting, 5 speed, with HANDBRAKE
```

Maybe try and build it this way. Also, you could try to use the `-X utf8` option (cf. python -h) to force the correct encoding.

**Comment by nlabiris** [comment] 2021-01-18 07:21
Thanks for the response.

Yes my locale is Greek. I'm using the latest version of the bundle (the one you linked).

Attached you can find the timerecord.log file.

I will check about the locale. Anyway. since this is not a bug you can close it. Thanks again.
[timerecord.log](https://github.com/soong-construction/dirt-rally-time-recorder/files/5828435/timerecord.log)

**Comment by maxbechtold** [comment] 2021-01-20 17:38
Thanks for the log, indeed the exception is not in there - but on second thought, it couldn't (the `UnicodeEncodeError` happened *during* logging, and python logging then goes into "safe mode" and falls back to sys.stderr output - which is what you got). Cf. https://docs.python.org/3.8/howto/logging.html#exceptions-raised-during-logging
Since this is the only clue about this error, I would not even change anything here. Unless I find a way to try and log the logging error (or anything) using a [custom handler](https://docs.python.org/3.8/library/logging.html#logging.Handler.handleError).

Any updates on how you actually launch the timerecorder and if maybe the `-X` flag helped would be much appreciated.

**Comment by nlabiris** [comment] 2021-01-20 18:30
I forgot to mention that I'm in a Windows platform so I need to figure out a few things before building from scratch.

I just downloaded the bundle and run the .exe file (double-click). No other commands involved.

Thanks for the info.

**Comment by maxbechtold** [comment] 2021-01-22 10:39
> I just downloaded the bundle and run the .exe file (double-click). No other commands involved.

This is crucial, because then the bundle is actually not as self-sustained as it should be...
I'm currently thinking it could be linked to the encoding the logging is set to. Currently, it seems to take the system locale (https://docs.python.org/3/library/logging.html#logging.basicConfig), which then causes encoding errors like yours for special characters. 

I could reproduce this by changing "Š" to a Greek character not in my default codepage, cf. below (the error message is printed properly, however) 
```
Ambiguous car data, 2 matches
ζkoda Fabia R5: SEQUENTIAL shifting, 5 speed, with HANDBRAKE
--- Logging error ---
Traceback (most recent call last):
  File "logging\__init__.py", line 1084, in emit
  File "c:\hostedtoolcache\windows\python\3.8.6\x64\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u03b6' in position 59: character maps to <undefined>
Call stack:
  File "timerecord.py", line 46, in <module>
  File "timerecord.py", line 36, in main
  File "asyncore.py", line 203, in loop
  File "asyncore.py", line 150, in poll
  File "asyncore.py", line 83, in read
  File "asyncore.py", line 418, in handle_read_event
  File "receiver.py", line 53, in handle_read
  File "receiver.py", line 58, in parse
  File "statsProcessor.py", line 106, in handleStats
  File "statsProcessor.py", line 180, in handleGameState
  File "statsProcessor.py", line 143, in startStage
  File "statsProcessor.py", line 78, in showCarControlInformation
  File "logging\__init__.py", line 1434, in info
  File "logging\__init__.py", line 1577, in _log
  File "logging\__init__.py", line 1587, in handle
  File "logging\__init__.py", line 1649, in callHandlers
  File "logging\__init__.py", line 950, in handle
  File "logging\__init__.py", line 1183, in emit
  File "logging\__init__.py", line 1089, in emit
Message: 'ζkoda Fabia R5: SEQUENTIAL shifting, 5 speed, with HANDBRAKE'
Arguments: ()
Volkswagen Polo GTI R5: SEQUENTIAL shifting, 5 speed, with HANDBRAKE
```

The logging should be fixed to UTF-8, but Python logging only support this in Python 3.9. This depends on #57.

For now, no action needs to be taken, as only the logging is hampered, but the recording and update scripts work. If you still want a workaround, use [encoding-fix.txt](https://github.com/soong-construction/dirt-rally-time-recorder/files/5855190/encoding-fix.txt) to change the problematic car name (start sqlite3.exe from the installation folder, enter `.read encoding-fix.txt`)

**Comment by nlabiris** [comment] 2021-01-26 20:25
Thanks. I think, as you said, the best solution is to use a default locale than relying on each system itself to avoid all kinds of issues that come with it.

**Comment by maxbechtold** [comment] 2021-02-07 15:06
I updated the labels, as this issue is not restricted to DiRT Rally 2.0, but is an issue with any car or track name containing characters outside the user's codepage - in particular Škoda and most of the Finland and Sweden tracks (containing the umlaut "ä").

The new version 2.10.3 provides a fix for this issue. Feel free to update @nlabiris. 

I should mention that the `list-laptimes.bat` will still not show characters outside your codepage properly, however this is not an issue with the `export-laptimes.bat` script (which only requires proper UTF-8 import into the chosen spreadsheet editor).

**Closed** 2021-03-23 06:03 UTC
Labels: bug
